### ISSUE TITLE
Handling of Inedible Plant Waste

### ISSUE THREAD

**Issue by JLefebvre55** [OpenFormTech/PeaPod#82]
Determine the process for the treatment and/or disposal of inedible plant waste.

NOTE: less trivial. maybe just grow fully edible plants?

1. Get the water out
2. Some kind of recycling?
3. ...
4. Fully waste product -> eject (the same way as human solid waste)

**Comment by nchareunsouk** [comment]
@JLefebvre55 @narvcharv 

- When grow cups are cleaned out, inedible waste is inserted into a macerator.
- The macerator grinds the waste into a pulp where it is mixed with water. 
- The pulp is extruded in a long cylinder with a pinhole running down the center.
- The cylinder is dried/dehydrated and cut into "scrap pucks" for use in  #77.

**Comment by nchareunsouk** [comment]
@JLefebvre55 @narvcharv @JonasMarshall 

**Option 1: Water Content Collection**
- Plant waste is collected by hand.
- Plant waste is macerated in a blender.
- Plant waste is dehydrated and water is collected.
- Dehydrated plant waste is ejected into space.


**Option 2: Subcritical Water Extraction (SWE)**
SWE is a process through which micro-nutrients and bioactive compounds can be extracted from plant matter and suspended in solution by using water instead of dangerous solvents. 

_Resources_
[Food waste: a potential bioresource for extraction of nutraceuticals and bioactive compounds](https://bioresourcesbioprocessing.springeropen.com/articles/10.1186/s40643-017-0148-6)
[Subcritical water extraction of bioactive compounds from Orostachys japonicus A. Berger (Crassulaceae)](https://www.nature.com/articles/s41598-020-67508-2)

- Plant waste is collected by hand.
- Plant waste is macerated in a blender.
- Plant waste goes through the process of subcritical water extraction.
- Plant waste is ejected after the extraction process.

**Comment by JLefebvre55** [comment]
@nchareunsouk I like that there's two options - let's present both, and potentially for Option 2 we could mention re-extraction of nutrients (not sure by what mechanism though. See #83
